language: java
jdk:
- oraclejdk8
addons:
  apt:
    sources:
    - mongodb-upstart
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
before_script:
- sleep 15
script: "./gradlew externalCiTest"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- test $TRAVIS_BRANCH = "master" && ./gradlew uploadArchives
before_install:
- openssl aes-256-cbc -K $encrypted_8a7269a7a25d_key -iv $encrypted_8a7269a7a25d_iv
  -in gradle.properties.enc -out .gradle/gradle.properties -d